lang:                  en
title:                 Saptarshi Nag
logo:                  /assets/img/circle-cropped-min.png
description:           Embedded System Engineer 
copyright:            
accent_image:          /assets/img/blog/Temple.jpg
accent_color:          rgb(79,177,186)
theme_color:           rgb(25, 55, 71)
tagline:               >
  <br /> A software Engineer's Coding Chronicles: Bytes of Wisdom.
    <br />

remote_theme: hydecorp/hydejack@v9.2.1

google_fonts:          Lora:700|Noto+Sans:400,400i,700,700i
font:                  Noto Sans, Helvetica, Arial, sans-serif
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif
font-code:             ui-monospace, Menlo, Monaco, "Cascadia Mono", "Segoe UI Mono", "Roboto Mono", "Oxygen Mono", "Ubuntu Monospace", "Source Code Pro", "Fira Mono", "Droid Sans Mono", "Courier New", monospace

hydejack:
  dark_mode:
    dynamic:           true
    sunrise:           6
    sunset:            18
    icon:              true
    always:            false
  post_addons:         [about, newsletter, related, random, comments]
  project_addons:      [about, newsletter, other, comments]
  no_mark_external:    false
  no_push_state:       true
  no_drawer:           true
  no_navbar:           true
  no_search:           true
  no_inline_css:       false
  no_page_style:       false
  no_break_layout:     false
  no_toc:              true
  no_third_column:     false
  no_large_headings:   true
  no_structured_data:  false
  no_theme_color:      false
  no_breadcrumbs:      false
  use_lsi:             true
  cookies_banner:      true
  advertise:           true
  hide_dates:          false
  hide_last_modified:  true
  no_clap_button:      true
  offline:
    enabled:           false
    cache_version:     1
    precache_assets:
      - /assets/img/swipe.svg

optional_front_matter:
  remove_originals:    true
readme_index:
  remove_originals:    true
  with_frontmatter:    true
relative_links:
  collections:         true
titles_from_headings:
  strip_title:         true
  collections:         true
compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]
sass:
  style:               compressed

menu:
 - title: Blog
   url: /blog/
 - title: My Projects
   url: /projects
 - title: Gallery 
   url: /image_gallery
 - title: My Resume
   url: /resume
 - title: Blog Category
   url: /resources

plugins:
  - jekyll-avatar
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-last-modified-at

collections:
  featured_categories:
    permalink:         /:name/
    output:            true

  featured_tags:
    permalink:         /tag-:name/
    output:            true

  projects:
    permalink:         /projects/:path/
    output:            true

  gallery:
    permalink:         /gallery/:path/
    output:            true

  linuz:
    permalink:         /linuz/:path/
    output:            true

  algonotes:
    permalink:         /algonotes/:path/
    output:            true

  edge:
    permalink:         /edge/:path/
    output:            true

permalink:             /blog/:categories/:year-:month-:day-:title/
paginate:              10
paginate_path:         /blog/page-:num/

author:
  picture:  /assets/img/me3.jpg
  social: 
    twitter: Saptarshi108
    kaggle: https://www.kaggle.com/saptarshinag01