lang:                  en
title:                 Saptarshi Nag
logo:                  /assets/img/circle-cropped-min.png
description:           Embedded System Engineer 
copyright:            
accent_image:          /assets/img/blog/Temple.jpg
accent_color:          rgb(79,177,186)
theme_color:           rgb(25, 55, 71)
tagline:               >
 <br />
  Embedded Software Developer | Research Student <br />
 
google_fonts:          Lora:400,400i
font:                  Lora
font_heading:          Bitter, serif;
font-code:             Fira Code, Menlo, Monaco, Consolas, monospa

hydejack:
 dark_mode: 
  dynamic: true
  sunrise: 6 
  sunset: 18
  icon: true
  always: true
  
  post_addons:         [about, newsletter, related, random, comments]
  project_addons:      [about, newsletter, other, comments]
  no_mark_external:    false
  no_push_state:       true
  no_drawer:           true
  no_navbar:           true
  no_search:           true
  no_inline_css:       false
  no_page_style:       false
  no_break_layout:     false
  no_toc:              true
  no_third_column:     false
  no_large_headings:   true
  no_structured_data:  false
  no_theme_color:      false
  no_breadcrumbs:      false
  use_lsi:             true
  cookies_banner:      true
  advertise:           true
  hide_dates:          false
  hide_last_modified:  false
   # Set to `true` if third party plugins fail to work with dynamically loaded pages
  no_push_state:       true

  # Set to `true` if you want to disable the drawer
  no_drawer:           true

  # Set to `true` if you don't to use the auto-hiding (JavaScript based) navbar.
  # Note that this will not hide the navbar completely, only replace it with a static one.
  # Use custom css to hide completely, e.g. `#_navbar { display: none }`.
  no_navbar:           true

  # Set to true to disable the built-in search functionality.
  # Note that search is disabled during local use to save on build time.
  # Run Jekyll with the `JEKYLL_ENV` environment variable set to `production` to enable.
  no_search:           true
  dark_mode:
    always:            false
    dynamic:           true
    sunrise:           6
    sunset:            18
    icon:              true
  offline:
    enabled:           false
    cache_version:     1
    precache_assets:
      - /assets/img/swipe.svg
optional_front_matter:
  remove_originals:    true
readme_index:
  remove_originals:    true
  with_frontmatter:    true
relative_links:
  collections:         true
titles_from_headings:
  strip_title:         true
  collections:         true
compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]
sass:
  style:               compressed
menu:
 
 - title: Blog &#8631;
   url: /blog/
   menu:
      - title:  "#Tags"
        url:    /tags/
      - title: "Category"
        url:    /resources
      #- title:  "&#10001; Timeline of Publish"
      # url:    /gallery/
 - title: My Resume
   url: /resume
 - title: Gallery 
   url: /image_gallery

 
   #url: /linuz
 - title: My Projects
   url: /projects/
 - title: Learning Resources
   url: /resources
 

plugins:
  - jekyll-avatar
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jekyll-feed
  
 
# Collections
# ----------------------------------------------------------------------------------------

collections:
  featured_categories:
    permalink:         /:name/
    output:            true

  featured_tags:
    permalink:         /tag-:name/
    output:            true

  projects:
    permalink:         /projects/:path/
    output:            true

  gallery:
    permalink:         /gallery/:path/
    output:            true

  linuz:
    permalink:         /linuz/:path/
    output:            true

  algonotes:
     permalink:         /algonotes/:path/
     output:            true
      
# Pagination configuration (used by the `blog` layout)
permalink:             /blog/:categories/:year-:month-:day-:title/

paginate:              10
paginate_path:         /blog/page-:num/



author: 
  picture:  /assets/img/me3.jpg
  social: 
   twitter: Saptarshi108
   github: saptarshi-max
   youtube: https://www.youtube.com/channel/UCW4aG2WzciPKa8NvWMrAfzg/videos
   kaggle: https://www.kaggle.com/saptarshinag01
